"""initial schema

Revision ID: 307a9b329b6a
Revises: 
Create Date: 2026-07-07 08:45:03.305006
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307a9b329b6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('WORKER', 'COMPANY', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=160), nullable=False),
    sa.Column('vat_number', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('vat_number')
    )
    op.create_table('worker_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profession', sa.Enum('ELETTRICISTA', 'IDRAULICO', 'MURATORE', 'CARPENTIERE', 'PIASTRELLISTA', 'FALEGNAME', 'IMBIANCHINO', 'SALDATORE', 'GRUISTA', 'TERMOIDRAULICO', 'CARTONGESSISTA', 'OPERATORE_ESCAVATORE', name='profession'), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('travel_radius_km', sa.Integer(), nullable=False),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('hourly_rate_min', sa.Integer(), nullable=False),
    sa.Column('hourly_rate_max', sa.Integer(), nullable=False),
    sa.Column('availability', sa.Enum('IMMEDIATE', 'WITHIN_WEEK', 'WITHIN_MONTH', 'NOT_LOOKING', name='availability_status'), nullable=False),
    sa.Column('ai_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('job_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('profession', sa.Enum('ELETTRICISTA', 'IDRAULICO', 'MURATORE', 'CARPENTIERE', 'PIASTRELLISTA', 'FALEGNAME', 'IMBIANCHINO', 'SALDATORE', 'GRUISTA', 'TERMOIDRAULICO', 'CARTONGESSISTA', 'OPERATORE_ESCAVATORE', name='profession'), nullable=False),
    sa.Column('job_type', sa.Enum('PERMANENT', 'TEMPORARY', 'FREELANCE', 'SUBCONTRACT', name='job_type'), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=False),
    sa.Column('salary_max', sa.Integer(), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('min_years_experience', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'FILLED', name='job_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'SHORTLISTED', 'INTERVIEW', 'HIRED', 'REJECTED', 'COMPLETED', name='application_status'), nullable=False),
    sa.Column('cover_message', sa.Text(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'worker_id', name='uq_application_job_worker')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('author_role', sa.String(length=16), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('punctuality', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('communication', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'author_role', name='uq_review_app_author')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('applications')
    op.drop_table('job_posts')
    op.drop_table('worker_profiles')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
