"""portfolio social photos likes comments

Revision ID: da763a65599f
Revises: f2f8ee4d874c
Create Date: 2026-07-19 08:56:27.260952
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da763a65599f'
down_revision: Union[str, None] = 'f2f8ee4d874c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_item_id'], ['portfolio_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_comments_portfolio_item_id'), 'portfolio_comments', ['portfolio_item_id'], unique=False)
    op.create_table('portfolio_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_item_id'], ['portfolio_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_item_id', 'user_id', name='uq_like_item_user')
    )
    op.create_index(op.f('ix_portfolio_likes_portfolio_item_id'), 'portfolio_likes', ['portfolio_item_id'], unique=False)
    op.create_index(op.f('ix_portfolio_likes_user_id'), 'portfolio_likes', ['user_id'], unique=False)
    op.create_table('portfolio_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_item_id', sa.Integer(), nullable=False),
    sa.Column('data_url', sa.Text(), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_item_id'], ['portfolio_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_photos_portfolio_item_id'), 'portfolio_photos', ['portfolio_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_photos_portfolio_item_id'), table_name='portfolio_photos')
    op.drop_table('portfolio_photos')
    op.drop_index(op.f('ix_portfolio_likes_user_id'), table_name='portfolio_likes')
    op.drop_index(op.f('ix_portfolio_likes_portfolio_item_id'), table_name='portfolio_likes')
    op.drop_table('portfolio_likes')
    op.drop_index(op.f('ix_portfolio_comments_portfolio_item_id'), table_name='portfolio_comments')
    op.drop_table('portfolio_comments')
    # ### end Alembic commands ###
